"""Stage 9C — SEC CompanyFacts Readiness Diagnostic v1.

Pure, no-IO diagnostic lens for SEC CompanyFacts research artifacts. Given
already-stored, sanitized metadata (LaneCoverage fields + safe observation
count), explains why the artifact is READY/LIMITED/SUPPRESSED/NOT_EVALUABLE
in compact, plain-English terms.

Distinguishes:
  stale_model_version
    Artifact was generated with a pre-Stage-9C model version
    (sec_xbrl_companyfacts_v1). Idempotency prevents re-generation until the
    model version changes. Re-run POST /intel/v3/run after this PR deploys to
    regenerate with sec_xbrl_companyfacts_v2.

  false_contradiction_candidate
    SUPPRESSED_CONTRADICTED + stale model version → likely caused by the
    pre-5H.3 generic group key that did not include unit/fy/fp/start/end/frame.
    Different XBRL durations or units were falsely grouped together as
    contradictions. Safe to re-run — the fix is already in the grouping code.

  true_contradiction
    SUPPRESSED_CONTRADICTED + current model version → genuinely conflicting
    XBRL values for the same complete identity (metric + unit + fy + fp +
    start + end + frame + filed). Expected for restatements or data quality
    issues in SEC filings.

  completeness_failure
    SUPPRESSED_INCOMPLETE: completeness band is THIN. Too few qualifying
    XBRL observations to meet the PARTIAL threshold. Usually caused by the
    SEC ticker having sparse filings or no matching allowlisted tags.

  missing_enrichment (NOT_EVALUABLE)
    Artifact written before Stage 5B-5E enrichment pipeline was active, so
    truth_usability_assessment / contradiction_assessment / completeness are
    absent in the stored payload. Re-run to regenerate with full enrichment.

  weak_authority (SUPPRESSED_UNKNOWN_SOURCE)
    All sources have UNKNOWN authority. Should not occur for SEC EDGAR
    artifacts (which use PRIMARY_AUTHORITY). Indicates very old artifact.

  stale_freshness (STALE_OR_UNKNOWN)
    Filed dates are over 180 days old. Artifact is present but outdated.

  limited
    USABLE_WITH_LIMITATIONS: partial coverage but usable. No action required
    unless STRONG coverage is needed.

  strong
    USABLE with primary authority: artifact is fully usable.

Hard constraints (non-negotiable):
  - Pure function. No IO, no DB, no LLM, no external calls.
  - Never imports or calls decide().
  - Never produces Buy/Hold/Trim/Sell authority.
  - safe_for_decision is always False.
  - No raw payloads, source URLs, fact values, API keys, or PII in output.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

DIAGNOSTIC_VERSION = "sec_companyfacts_readiness_diagnostic.v1"

# The current model version after the Stage 9C idempotency-key bump.
# Artifacts with any other model_version were generated by older code.
SEC_COMPANYFACTS_CURRENT_MODEL_VERSION = "sec_xbrl_companyfacts_v2"
SEC_COMPANYFACTS_PREV_MODEL_VERSION = "sec_xbrl_companyfacts_v1"

# Readiness category labels (safe, plain-English).
CATEGORY_STRONG = "STRONG"
CATEGORY_LIMITED = "LIMITED"
CATEGORY_SUPPRESSED_CONTRADICTED = "SUPPRESSED_CONTRADICTED"
CATEGORY_SUPPRESSED_INCOMPLETE = "SUPPRESSED_INCOMPLETE"
CATEGORY_SUPPRESSED_UNKNOWN_SOURCE = "SUPPRESSED_UNKNOWN_SOURCE"
CATEGORY_NOT_EVALUABLE = "NOT_EVALUABLE"
CATEGORY_STALE_OR_UNKNOWN = "STALE_OR_UNKNOWN"
CATEGORY_MISSING = "MISSING"

# Authority levels that qualify a USABLE artifact as STRONG.
_STRONG_AUTHORITY_LEVELS = frozenset({"PRIMARY_AUTHORITY", "OFFICIAL_FREE_SOURCE"})

_SUPPRESSED_PREFIX = "SUPPRESSED_"


@dataclass
class SecCompanyFactsReadinessDiagnostic:
    """Safe per-artifact diagnostic for SEC CompanyFacts readiness.

    All fields are safe for diagnostics output: counts, booleans, enum labels,
    plain-English strings. No raw payloads, no source URLs, no fact values.

    safe_for_decision is permanently False — this is diagnostic context only.
    """

    diagnostic_version: str
    artifact_id: Optional[str]
    generated_at: Optional[str]
    model_version: Optional[str]
    observation_count: Optional[int]     # COUNT from research_artifact_facts
    freshness_status: Optional[str]
    source_authority: Optional[str]
    completeness_band: Optional[str]
    usability_label: Optional[str]
    suppression_reason: Optional[str]
    contradiction_evaluable: Optional[bool]
    contradiction_count: Optional[int]
    not_evaluable_reason: Optional[str]  # from contradiction_assessment
    readiness_category: str              # see CATEGORY_* constants above
    is_stale_model_version: bool
    is_false_contradiction_candidate: bool
    diagnosis_note: str
    safe_for_decision: bool = False      # always False

    def to_dict(self) -> dict[str, Any]:
        return {
            "diagnostic_version": self.diagnostic_version,
            "artifact_id": self.artifact_id,
            "generated_at": self.generated_at,
            "model_version": self.model_version,
            "observation_count": self.observation_count,
            "freshness_status": self.freshness_status,
            "source_authority": self.source_authority,
            "completeness_band": self.completeness_band,
            "usability_label": self.usability_label,
            "suppression_reason": self.suppression_reason,
            "contradiction_evaluable": self.contradiction_evaluable,
            "contradiction_count": self.contradiction_count,
            "not_evaluable_reason": self.not_evaluable_reason,
            "readiness_category": self.readiness_category,
            "is_stale_model_version": self.is_stale_model_version,
            "is_false_contradiction_candidate": self.is_false_contradiction_candidate,
            "diagnosis_note": self.diagnosis_note,
            "safe_for_decision": self.safe_for_decision,
        }


def diagnose_sec_companyfacts_readiness(
    *,
    artifact_id: Optional[str],
    generated_at: Optional[str],
    model_version: Optional[str],
    observation_count: Optional[int],
    freshness_status: Optional[str],
    source_authority: Optional[str],
    completeness_band: Optional[str],
    usability_label: Optional[str],
    suppression_reason: Optional[str],
    contradiction_evaluable: Optional[bool],
    contradiction_count: Optional[int],
    not_evaluable_reason: Optional[str],
) -> SecCompanyFactsReadinessDiagnostic:
    """Build a safe diagnostic for one SEC CompanyFacts artifact.

    All inputs come from already-stored, sanitized metadata (LaneCoverage
    fields + fact_count from the facts table). No raw payloads or fact values.

    Returns SecCompanyFactsReadinessDiagnostic — always non-None, never raises.
    """
    is_stale_model = _is_stale_model_version(model_version)
    readiness_category = _classify_readiness_category(
        usability_label=usability_label,
        freshness_status=freshness_status,
        source_authority=source_authority,
    )
    is_false_contradiction_candidate = (
        readiness_category == CATEGORY_SUPPRESSED_CONTRADICTED and is_stale_model
    )
    diagnosis_note = _build_diagnosis_note(
        readiness_category=readiness_category,
        is_stale_model=is_stale_model,
        is_false_contradiction_candidate=is_false_contradiction_candidate,
        freshness_status=freshness_status,
        not_evaluable_reason=not_evaluable_reason,
        contradiction_count=contradiction_count,
        model_version=model_version,
    )
    return SecCompanyFactsReadinessDiagnostic(
        diagnostic_version=DIAGNOSTIC_VERSION,
        artifact_id=artifact_id,
        generated_at=generated_at,
        model_version=model_version,
        observation_count=observation_count,
        freshness_status=freshness_status,
        source_authority=source_authority,
        completeness_band=completeness_band,
        usability_label=usability_label,
        suppression_reason=suppression_reason,
        contradiction_evaluable=contradiction_evaluable,
        contradiction_count=contradiction_count,
        not_evaluable_reason=not_evaluable_reason,
        readiness_category=readiness_category,
        is_stale_model_version=is_stale_model,
        is_false_contradiction_candidate=is_false_contradiction_candidate,
        diagnosis_note=diagnosis_note,
        safe_for_decision=False,
    )


# ── Internal helpers ──────────────────────────────────────────────────────────


def _is_stale_model_version(model_version: Optional[str]) -> bool:
    """True when model_version is absent or not the current post-9C version."""
    if not model_version:
        return True
    return model_version != SEC_COMPANYFACTS_CURRENT_MODEL_VERSION


def _classify_readiness_category(
    *,
    usability_label: Optional[str],
    freshness_status: Optional[str],
    source_authority: Optional[str],
) -> str:
    """Map stored metadata to a readiness category."""
    if usability_label is None:
        return CATEGORY_NOT_EVALUABLE

    if usability_label == "USABLE":
        if _is_stale_freshness(freshness_status):
            return CATEGORY_STALE_OR_UNKNOWN
        if source_authority in _STRONG_AUTHORITY_LEVELS:
            return CATEGORY_STRONG
        return CATEGORY_LIMITED

    if usability_label == "USABLE_WITH_LIMITATIONS":
        if _is_stale_freshness(freshness_status):
            return CATEGORY_STALE_OR_UNKNOWN
        return CATEGORY_LIMITED

    if "SUPPRESSED_CONTRADICTED" in (usability_label or ""):
        return CATEGORY_SUPPRESSED_CONTRADICTED

    if "SUPPRESSED_INCOMPLETE" in (usability_label or ""):
        return CATEGORY_SUPPRESSED_INCOMPLETE

    if "SUPPRESSED_UNKNOWN_SOURCE" in (usability_label or ""):
        return CATEGORY_SUPPRESSED_UNKNOWN_SOURCE

    if (usability_label or "").startswith(_SUPPRESSED_PREFIX):
        return CATEGORY_SUPPRESSED_INCOMPLETE  # conservative fallback

    if usability_label == "NOT_EVALUABLE":
        return CATEGORY_NOT_EVALUABLE

    return CATEGORY_NOT_EVALUABLE


def _is_stale_freshness(freshness_status: Optional[str]) -> bool:
    if not isinstance(freshness_status, str):
        return True
    return freshness_status.upper() in {"STALE", "UNKNOWN"}


def _build_diagnosis_note(
    *,
    readiness_category: str,
    is_stale_model: bool,
    is_false_contradiction_candidate: bool,
    freshness_status: Optional[str],
    not_evaluable_reason: Optional[str],
    contradiction_count: Optional[int],
    model_version: Optional[str],
) -> str:
    """Return a plain-English diagnosis note."""
    stale_note = ""
    if is_stale_model:
        mv = model_version or "unknown"
        stale_note = (
            f" Artifact was generated with model_version={mv!r} "
            f"(current: {SEC_COMPANYFACTS_CURRENT_MODEL_VERSION!r}). "
            "Re-run POST /intel/v3/run with INTEL_V3_SEC_COMPANYFACTS_EVIDENCE_ENABLED=true "
            "to regenerate with the current contradiction-grouping fix."
        )

    if readiness_category == CATEGORY_STRONG:
        return (
            "SEC CompanyFacts artifact is STRONG: USABLE with primary authority "
            "and fresh XBRL filings."
        )

    if readiness_category == CATEGORY_LIMITED:
        return (
            "SEC CompanyFacts artifact is LIMITED (USABLE_WITH_LIMITATIONS): "
            "partial coverage but usable for downstream analysis."
            + stale_note
        )

    if readiness_category == CATEGORY_STALE_OR_UNKNOWN:
        return (
            f"SEC CompanyFacts freshness is {freshness_status or 'UNKNOWN'}. "
            "Filed dates are stale (>180 days) or unknown. "
            "Re-run Intel v3 to fetch updated XBRL data."
            + stale_note
        )

    if readiness_category == CATEGORY_SUPPRESSED_CONTRADICTED:
        count_note = (
            f" ({contradiction_count} conflict group(s))" if contradiction_count else ""
        )
        if is_false_contradiction_candidate:
            return (
                f"SUPPRESSED_CONTRADICTED{count_note}: likely a false contradiction "
                "from pre-Stage-5H.3 grouping. The old group key omitted "
                "unit/fy/fp/period_start/period_end/frame, so distinct XBRL "
                "durations or units were incorrectly grouped together."
                + stale_note.strip()
            )
        return (
            f"SUPPRESSED_CONTRADICTED{count_note}: contradiction detected by current "
            "grouping. Two or more XBRL observations for the same complete identity "
            "(metric + unit + fy + fp + start + end + frame + filed) report conflicting "
            "values. Expected for restatements; investigate SEC filings for this ticker."
            + stale_note
        )

    if readiness_category == CATEGORY_SUPPRESSED_INCOMPLETE:
        return (
            "SUPPRESSED_INCOMPLETE: evidence completeness band is THIN. "
            "Insufficient qualifying XBRL observations to meet the PARTIAL "
            "completeness threshold. Check SEC_EDGAR_USER_AGENT is set, the "
            "ticker has 10-K/10-Q filings, and the allowlisted us-gaap tags "
            "are present in the company's taxonomy."
            + stale_note
        )

    if readiness_category == CATEGORY_SUPPRESSED_UNKNOWN_SOURCE:
        return (
            "SUPPRESSED_UNKNOWN_SOURCE: all sources have UNKNOWN authority. "
            "Should not occur for SEC EDGAR artifacts — indicates an artifact "
            "written before Stage 5B source credibility enrichment."
            + stale_note
        )

    if readiness_category == CATEGORY_NOT_EVALUABLE:
        ne_reason = not_evaluable_reason or "not_specified"
        if is_stale_model:
            return (
                f"NOT_EVALUABLE (not_evaluable_reason={ne_reason!r}): enrichment "
                "metadata is absent or incomplete — artifact was likely written "
                "before the Stage 5B-5E truth enrichment pipeline was applied."
                + stale_note
            )
        return (
            f"NOT_EVALUABLE (not_evaluable_reason={ne_reason!r}): "
            "truth adapter metadata is missing or facts are not comparable. "
            "Re-run Intel v3 to regenerate with full enrichment."
        )

    return f"Unknown readiness category: {readiness_category}."
