"""Phase 9 — SEC Metric Evidence Readiness Adapter.

Purpose:
    Inspects existing Phase 8 SEC metric evidence (generated by Phases 8A–8F) and
    classifies each portfolio ticker into a typed readiness status for future
    Intel v3 truth-adapter input consumption.

    Answers:
        "For each portfolio ticker, what is the SEC metric evidence readiness state
        for future consumption, and why?"

    Does NOT answer:
        "What should the visible Buy/Hold/Trim/Sell action be?"

    Readiness statuses:
        READY               — all expected metric bucket groups covered.
        PARTIAL             — some buckets present, some groups missing.
        BLOCKED             — no source-linked SEC metric evidence (never attempted,
                              or attempted with zero source-linked facts).
        SKIPPED_NON_COMPANY — ETF/fund/crypto/index ticker not eligible for SEC
                              metric coverage.

    This is a shadow/readiness-only layer. It does NOT:
        - Feed SEC metrics into DecisionInputV3.
        - Change visible Buy/Hold/Trim/Sell decisions.
        - Invoke SEC coverage expansion write mode.
        - Retry BLSH/KLAR/TSM-style tickers.
        - Create or modify intel_v3_snapshots.

    Future Phase 10 can depend on this readiness contract after explicit approval.

Architecture invariants (non-negotiable):
    - NEVER imports or calls decide() from decision_policy_v1.
    - NEVER imports IntelV3Service, recommendation_engine, or any frontend path.
    - NEVER writes to any DB table.
    - NEVER calls any SEC provider, LLM, or external service.
    - NEVER returns raw metric values, structured_payload, source URLs, excerpts.
    - NEVER returns raw DB rows.
    - NEVER sets safe_for_decision=True.
    - safe_for_decision is always False.
    - visible_snapshot_unchanged is always True.
    - Any exception triggers a safe disabled result — never propagates to callers.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

from .sec_metric_candidate_classifier import classify_sec_metric_candidate
from .sec_metric_portfolio_coverage_dry_run import build_portfolio_sec_coverage_dry_run
from .sec_metric_truth_adapter_dry_run import run_sec_metric_truth_adapter_dry_run
from .sec_metric_evidence_snapshot_dry_run import run_sec_metric_evidence_snapshot_dry_run

logger = logging.getLogger(__name__)

SEC_METRIC_EVIDENCE_READINESS_CONTRACT_VERSION = "phase9_v1"

# Stable readiness status values — contract for future Phase 10 consumption.
READINESS_STATUS_READY = "READY"
READINESS_STATUS_PARTIAL = "PARTIAL"
READINESS_STATUS_BLOCKED = "BLOCKED"
READINESS_STATUS_SKIPPED_NON_COMPANY = "SKIPPED_NON_COMPANY"

# Phase 8B future_adapter_readiness values that map to READY/PARTIAL.
_PHASE8B_READY = "READY_DRY_RUN_ONLY"
_PHASE8B_PARTIAL = "PARTIAL_DRY_RUN_ONLY"

# Blocking codes always present on every ticker — not specific to the individual
# ticker's readiness state, so excluded from blocked_tickers_with_reason output.
_ALWAYS_BLOCKING_CODES: frozenset[str] = frozenset({
    "decision_consumption_disabled",
    "safe_for_decision_db_lock",
})


@dataclass
class SecMetricEvidenceReadinessResult:
    """Typed aggregate-only Phase 9 SEC metric evidence readiness result.

    All fields are safe to log and return via the diagnostics endpoint.

    Forbidden (never present in any field):
        - raw metric values
        - full structured_payload dicts
        - raw source URLs or excerpts
        - raw DB rows
        - Buy/Hold/Trim/Sell signals or recommendations
        - user-facing UI copy

    Invariants:
        safe_for_decision is always False.
        visible_snapshot_unchanged is always True.
    """
    adapter_enabled: bool
    safe_for_decision: bool                                     # always False
    visible_snapshot_unchanged: bool                            # always True
    portfolio_ticker_count: int
    ready_count: int
    partial_count: int
    blocked_count: int
    skipped_non_company_count: int
    ready_tickers: list[str]                                    # sorted
    partial_tickers_with_missing_groups: dict[str, list[str]]  # ticker → sorted missing groups
    blocked_tickers_with_reason: dict[str, list[str]]          # ticker → sorted reason codes
    skipped_tickers_by_reason: dict[str, list[str]]            # reason → sorted ticker list
    errors: list[str] = field(default_factory=list)


def _disabled_result(reason: str) -> SecMetricEvidenceReadinessResult:
    """Return a no-op result when the adapter is disabled."""
    return SecMetricEvidenceReadinessResult(
        adapter_enabled=False,
        safe_for_decision=False,
        visible_snapshot_unchanged=True,
        portfolio_ticker_count=0,
        ready_count=0,
        partial_count=0,
        blocked_count=0,
        skipped_non_company_count=0,
        ready_tickers=[],
        partial_tickers_with_missing_groups={},
        blocked_tickers_with_reason={},
        skipped_tickers_by_reason={},
        errors=[reason],
    )


def build_sec_metric_evidence_readiness(
    portfolio_positions: list[dict],
    snapshot_by_ticker: dict[str, dict],
) -> SecMetricEvidenceReadinessResult:
    """Pure, deterministic, read-only Phase 9 readiness adapter.

    Classifies each portfolio ticker into a readiness status based on existing
    Phase 8B SEC metric evidence snapshot output. Reuses Phase 8D's tested
    portfolio coverage builder for per-ticker diagnostic data.

    Args:
        portfolio_positions: List of dicts with 'ticker' and optionally 'category'.
                             category values: Crypto|Core|ETF|Other|IPO|SELL.
        snapshot_by_ticker:  Phase 8B by_ticker output (ticker → evidence snapshot dict).
                             Tickers absent from this dict have no research artifacts.

    Returns:
        SecMetricEvidenceReadinessResult with typed per-category aggregates.
        safe_for_decision is always False.
        visible_snapshot_unchanged is always True.

    Never:
        - Imports or calls decide() / decision_policy_v1.
        - Imports IntelV3Service, recommendation_engine, or any frontend path.
        - Writes to any DB table.
        - Returns raw metric values, structured_payload, source URLs.
        - Sets safe_for_decision=True.
    """
    try:
        return _build(portfolio_positions, snapshot_by_ticker)
    except Exception:  # noqa: BLE001
        return SecMetricEvidenceReadinessResult(
            adapter_enabled=True,
            safe_for_decision=False,
            visible_snapshot_unchanged=True,
            portfolio_ticker_count=0,
            ready_count=0,
            partial_count=0,
            blocked_count=0,
            skipped_non_company_count=0,
            ready_tickers=[],
            partial_tickers_with_missing_groups={},
            blocked_tickers_with_reason={},
            skipped_tickers_by_reason={},
            errors=["readiness_build_error"],
        )


def _build(
    portfolio_positions: list[dict],
    snapshot_by_ticker: dict[str, dict],
) -> SecMetricEvidenceReadinessResult:
    # Reuse Phase 8D's tested portfolio coverage builder to obtain per-ticker
    # diagnostic data (future_adapter_readiness, missing_buckets, blocking_reason_codes).
    coverage = build_portfolio_sec_coverage_dry_run(
        portfolio_positions=portfolio_positions,
        snapshot_by_ticker=snapshot_by_ticker,
        coverage_enabled=True,
    )

    # Deduplicate portfolio tickers, preserving first-seen category.
    seen: dict[str, str] = {}
    for pos in portfolio_positions:
        ticker = str(pos.get("ticker") or "").upper().strip()
        category = str(pos.get("category") or "")
        if ticker and ticker not in seen:
            seen[ticker] = category

    ready_tickers: list[str] = []
    partial_tickers_with_missing_groups: dict[str, list[str]] = {}
    blocked_tickers_with_reason: dict[str, list[str]] = {}
    skipped_reason_to_tickers: dict[str, list[str]] = {}

    for ticker in sorted(seen.keys()):
        category = seen[ticker]
        ticker_data = coverage.by_ticker.get(ticker, {})
        blocking_codes: set[str] = set(ticker_data.get("blocking_reason_codes") or [])
        future_readiness = str(ticker_data.get("future_adapter_readiness") or "BLOCKED_DRY_RUN_ONLY")
        missing_buckets: list[str] = list(ticker_data.get("missing_buckets") or [])

        # Classification priority: non-company check first (same as Phase 8F classifier).
        clf = classify_sec_metric_candidate(ticker, category)
        if not clf["is_sec_company_candidate"]:
            # SKIPPED_NON_COMPANY — group by specific sub-reason.
            clf_codes = clf["blocking_reason_codes"]
            sub_reason = "likely_crypto" if "likely_crypto" in clf_codes else "likely_fund_or_etf"
            skipped_reason_to_tickers.setdefault(sub_reason, []).append(ticker)

        elif future_readiness == _PHASE8B_READY:
            ready_tickers.append(ticker)

        elif future_readiness == _PHASE8B_PARTIAL:
            partial_tickers_with_missing_groups[ticker] = sorted(missing_buckets)

        else:
            # BLOCKED — include ticker-specific diagnostic codes only,
            # excluding always-present safety codes that apply to every ticker.
            specific_codes = sorted(blocking_codes - _ALWAYS_BLOCKING_CODES)
            if not specific_codes:
                specific_codes = ["blocked_no_source_linked_sec_metric_evidence"]
            blocked_tickers_with_reason[ticker] = specific_codes

    for reason in skipped_reason_to_tickers:
        skipped_reason_to_tickers[reason].sort()

    ready_count = len(ready_tickers)
    partial_count = len(partial_tickers_with_missing_groups)
    blocked_count = len(blocked_tickers_with_reason)
    skipped_non_company_count = sum(len(v) for v in skipped_reason_to_tickers.values())

    return SecMetricEvidenceReadinessResult(
        adapter_enabled=True,
        safe_for_decision=False,
        visible_snapshot_unchanged=True,
        portfolio_ticker_count=len(seen),
        ready_count=ready_count,
        partial_count=partial_count,
        blocked_count=blocked_count,
        skipped_non_company_count=skipped_non_company_count,
        ready_tickers=sorted(ready_tickers),
        partial_tickers_with_missing_groups=partial_tickers_with_missing_groups,
        blocked_tickers_with_reason=blocked_tickers_with_reason,
        skipped_tickers_by_reason=dict(sorted(skipped_reason_to_tickers.items())),
        errors=[],
    )


def compute_sec_readiness_for_phase11_adapter(
    user_id: str,
    db_client: Any,
) -> SecMetricEvidenceReadinessResult:
    """Compute Phase 9 SEC metric readiness for Phase 11 adapter consumption.

    Unlike compute_sec_metric_evidence_readiness(), this function has no Phase 9
    kill switch dependency. The Phase 11 adapter has its own kill switch
    (intel_v3_sec_metric_truth_adapter_v1_enabled) and calls this directly.

    Returns SecMetricEvidenceReadinessResult regardless of outcome. Never raises.

    Never:
        - Writes to any DB table.
        - Calls SEC providers, LLMs, decide(), IntelV3Service.
        - Returns raw metric values, structured_payload, source URLs.
        - Sets safe_for_decision=True.
    """
    errors: list[str] = []
    try:
        return _compute(user_id=user_id, db_client=db_client, errors=errors)
    except Exception as exc:  # noqa: BLE001
        logger.error(
            "sec_readiness_for_phase11_error user_id=%s error=%s", user_id, exc
        )
        return SecMetricEvidenceReadinessResult(
            adapter_enabled=True,
            safe_for_decision=False,
            visible_snapshot_unchanged=True,
            portfolio_ticker_count=0,
            ready_count=0,
            partial_count=0,
            blocked_count=0,
            skipped_non_company_count=0,
            ready_tickers=[],
            partial_tickers_with_missing_groups={},
            blocked_tickers_with_reason={},
            skipped_tickers_by_reason={},
            errors=errors + [f"compute_error error={exc}"],
        )


def compute_sec_metric_evidence_readiness(
    user_id: str,
    db_client: Any,
    settings: Any = None,
) -> SecMetricEvidenceReadinessResult:
    """Read portfolio tickers and research artifacts, then compute Phase 9 readiness.

    Returns SecMetricEvidenceReadinessResult regardless of outcome. Never raises.

    Kill switch:
        settings.intel_v3_sec_metric_evidence_readiness_adapter_enabled must be True.

    This function:
        - Reads portfolio positions (ticker, category) from 'positions' table.
        - Falls back to 'portfolio_snapshots' positions_data if positions empty.
        - Reads research artifacts for portfolio tickers.
        - Reads facts for those artifacts.
        - Runs Phase 8A (sec_metric_truth_adapter_dry_run).
        - Runs Phase 8B (sec_metric_evidence_snapshot_dry_run).
        - Calls build_sec_metric_evidence_readiness() to produce typed readiness.

    Never:
        - Writes to any DB table.
        - Calls SEC providers, LLMs, decide(), IntelV3Service.
        - Returns raw metric values, structured_payload, source URLs.
        - Sets safe_for_decision=True.
    """
    if settings is None:
        from app.config import get_settings
        settings = get_settings()

    if not getattr(settings, "intel_v3_sec_metric_evidence_readiness_adapter_enabled", False):
        return _disabled_result(
            "intel_v3_sec_metric_evidence_readiness_adapter_enabled=false"
        )

    errors: list[str] = []

    try:
        return _compute(user_id=user_id, db_client=db_client, errors=errors)
    except Exception as exc:  # noqa: BLE001
        logger.error(
            "sec_metric_evidence_readiness_error user_id=%s error=%s", user_id, exc
        )
        return SecMetricEvidenceReadinessResult(
            adapter_enabled=True,
            safe_for_decision=False,
            visible_snapshot_unchanged=True,
            portfolio_ticker_count=0,
            ready_count=0,
            partial_count=0,
            blocked_count=0,
            skipped_non_company_count=0,
            ready_tickers=[],
            partial_tickers_with_missing_groups={},
            blocked_tickers_with_reason={},
            skipped_tickers_by_reason={},
            errors=errors + [f"compute_error error={exc}"],
        )


def _compute(
    user_id: str,
    db_client: Any,
    errors: list[str],
) -> SecMetricEvidenceReadinessResult:
    # ── Step 1: Read portfolio positions ──────────────────────────────────────
    portfolio_positions: list[dict] = []
    try:
        pos_result = (
            db_client.table("positions")
            .select("ticker,category")
            .eq("user_id", user_id)
            .execute()
        )
        raw_positions = list(pos_result.data or [])
        portfolio_positions = [
            {
                "ticker": str(r.get("ticker") or ""),
                "category": str(r.get("category") or ""),
            }
            for r in raw_positions
            if r.get("ticker")
        ]
    except Exception as exc:  # noqa: BLE001
        errors.append(f"portfolio_positions_query_error error={exc}")

    # Fallback: portfolio_snapshots.positions_data (most recent snapshot).
    if not portfolio_positions:
        try:
            snap_result = (
                db_client.table("portfolio_snapshots")
                .select("positions_data")
                .eq("user_id", user_id)
                .order("snapshot_at", desc=True)
                .limit(1)
                .execute()
            )
            if snap_result.data:
                raw_snap = snap_result.data[0] or {}
                raw_positions_data = raw_snap.get("positions_data") or []
                if isinstance(raw_positions_data, list):
                    for row in raw_positions_data:
                        if isinstance(row, dict) and row.get("ticker"):
                            portfolio_positions.append(
                                {
                                    "ticker": str(row["ticker"]),
                                    "category": str(row.get("category") or ""),
                                }
                            )
        except Exception as exc:  # noqa: BLE001
            errors.append(f"portfolio_snapshots_query_error error={exc}")

    # Deduplicate portfolio tickers for artifact query.
    portfolio_tickers = list(
        dict.fromkeys(
            p["ticker"].upper().strip()
            for p in portfolio_positions
            if p.get("ticker", "").strip()
        )
    )

    # ── Step 2: Read research artifacts for portfolio tickers ─────────────────
    artifact_rows: list[dict] = []
    if portfolio_tickers:
        try:
            art_result = (
                db_client.table("research_artifacts")
                .select(
                    "id,ticker,artifact_type,skill_pack,"
                    "safe_for_decision,is_active,created_at"
                )
                .eq("user_id", user_id)
                .in_("ticker", portfolio_tickers)
                .execute()
            )
            artifact_rows = list(art_result.data or [])
        except Exception as exc:  # noqa: BLE001
            errors.append(f"research_artifacts_query_error error={exc}")

    # ── Step 3: Read facts for those artifacts ────────────────────────────────
    facts_by_artifact: dict[str, list[dict]] = {}
    if artifact_rows:
        artifact_ids = [str(r["id"]) for r in artifact_rows if r.get("id")]
        if artifact_ids:
            try:
                fact_result = (
                    db_client.table("research_artifact_facts")
                    .select("id,artifact_id,fact_kind,structured_payload,source_id")
                    .eq("user_id", user_id)
                    .in_("artifact_id", artifact_ids)
                    .execute()
                )
                for row in (fact_result.data or []):
                    aid = str(row.get("artifact_id", ""))
                    if aid:
                        facts_by_artifact.setdefault(aid, []).append(row)
            except Exception as exc:  # noqa: BLE001
                errors.append(f"research_artifact_facts_query_error error={exc}")

    # ── Step 4: Run Phase 8A ──────────────────────────────────────────────────
    adapter_result = run_sec_metric_truth_adapter_dry_run(
        artifact_rows=artifact_rows,
        facts_by_artifact=facts_by_artifact,
    )

    # ── Step 5: Run Phase 8B ──────────────────────────────────────────────────
    snapshot_result = run_sec_metric_evidence_snapshot_dry_run(
        adapter_result=adapter_result,
        artifact_rows=artifact_rows,
        facts_by_artifact=facts_by_artifact,
    )

    # ── Step 6: Build Phase 9 readiness ──────────────────────────────────────
    result = build_sec_metric_evidence_readiness(
        portfolio_positions=portfolio_positions,
        snapshot_by_ticker=snapshot_result.by_ticker,
    )

    result.errors.extend(errors)
    return result
