[theme]
primaryColor = "#00f0aa"
backgroundColor = "#0a0e14"
secondaryBackgroundColor = "#131820"
textColor = "#e8ecf8"
font = "monospace"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
